### ISSUE TITLE
Adding package versions to outputs from evaluation and (potentially) inference

### ISSUE THREAD

**Issue by adamklie** [EngreitzLab/gene_network_evaluation#20]
Display all the package versions used for inference and evaluation on a tab of the dashboard. Is this something that snakemake can easily do (or already does)?

Would just be a file output to the evaluations directory like `versions.yaml` or something. Here is an example I made up for the iPSC data:

```yaml
inference_software_versions:
  cnmf: 0.0.q
  numpy: 1.20.2
  pandas: 1.2.4
evaluation_software_versions:
  gene_program_evaluation: 0.0.1
  mudata: 0.0.1
  joblib: 1.0.1
  scipy: 1.6.2
  numpy: 1.20.2
  pandas: 1.2.4
  scikit-learn: 0.24.2
  scikit-posthocs: 0.6.6
  seaborn: 0.11.1
  gseapy: 0.10.1
  pymemesuite: 0.0.1
  google-cloud-bigquery: 2.26.0
```

But we can pretty much do anything as long as it's consistent and makes sense.
