### ISSUE TITLE
Align dashboard with config from evaluation pipeline

### ISSUE THREAD

**Issue by adamklie** [EngreitzLab/gene_network_evaluation#27]
Have th pipeline dump a `config.yaml` in the output directory that I can use for the dashboard. Here is an example:

```yaml
output_loc: /cellar/users/aklie/opt/gene_program_evaluation/dashapp/example_data/iPSC_EC_evaluations/cNMF_60_0.2_gene_names.h5mu
categorical_keys: ['sample']
continuous_keys: None
dim_reduce_keys: None
workdir: /cellar/users/aklie/opt/gene_program_evaluation/dashapp/example_data/iPSC_EC_evaluations
data_key: rna
annotations_loc: "annotations.csv"  # if none defaults to annotations.csv
```

User can manually add a location for annotations to be dumped as above. Otherwise it defaults to eval directory.

This is important for things like:

1. Knowing what categorical keys to plot
2. Knowing what the inference key (data_key) was
